import { StyleSheet } from 'react-native';
import { DS } from '../../../constants/ds';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: DS.bg },
  scroll: { padding: 20, paddingTop: 20, paddingBottom: 40 },

  sectionLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: DS.text3,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  divider: {
    height: 1,
    backgroundColor: DS.border,
    marginBottom: 16,
  },
  successText: {
    fontSize: 13,
    color: '#22C55E',
    fontWeight: '500',
    marginBottom: 12,
  },
  card: {
    backgroundColor: DS.bg,
    borderWidth: 1,
    borderColor: DS.border,
    borderRadius: 8,
    padding: 20,
    marginBottom: 20,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  cardTitle: { fontSize: 14, fontWeight: '600', color: DS.text1, marginBottom: 4 },
  cardSub: { fontSize: 12, color: DS.text2 },

  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 6,
    borderWidth: 1,
  },
  badgeEnabled: { backgroundColor: 'rgba(34,197,94,0.1)', borderColor: 'rgba(34,197,94,0.3)' },
  badgeDisabled: { backgroundColor: DS.surface2, borderColor: DS.border },
  badgeDot: { width: 5, height: 5, borderRadius: 3 },
  badgeLabel: { fontSize: 11, fontWeight: '600' },

  infoBox: {
    backgroundColor: DS.surface2,
    borderWidth: 1,
    borderColor: DS.border,
    borderRadius: 8,
    padding: 12,
    marginBottom: 14,
  },
  infoText: { fontSize: 12, color: DS.text2, lineHeight: 18 },

  enableBtn: {
    backgroundColor: DS.surface3,
    borderWidth: 1,
    borderColor: DS.border2,
    borderRadius: 8,
    padding: 13,
    alignItems: 'center',
  },
  enableBtnLabel: { fontSize: 14, fontWeight: '500', color: DS.text1 },
  disableBtn: {
    backgroundColor: 'rgba(239,68,68,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.2)',
    borderRadius: 8,
    padding: 13,
    alignItems: 'center',
  },
  disableBtnLabel: { fontSize: 14, fontWeight: '500', color: DS.red },

  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  sheetWrapper: { justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: DS.bg,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: DS.border2,
    padding: 24,
    paddingTop: 12,
  },
  handle: { width: 36, height: 4, borderRadius: 2, backgroundColor: DS.border2, alignSelf: 'center', marginBottom: 24 },
  sheetTitle: { fontSize: 17, fontWeight: '700', color: DS.text1, letterSpacing: -0.4, marginBottom: 6 },
  sheetSubtitle: { fontSize: 13, color: DS.text2, lineHeight: 19, marginBottom: 20, letterSpacing: -0.15 },
  sheetActions: { flexDirection: 'row' },

  qrPlaceholder: {
    width: 160, height: 160, borderRadius: 8,
    backgroundColor: DS.surface2, borderWidth: 1, borderColor: DS.border2,
    alignSelf: 'center', alignItems: 'center', justifyContent: 'center', marginBottom: 16,
  },
  qrWrap: { alignItems: 'center', marginBottom: 12 },
  qrImage: { width: 160, height: 160, borderRadius: 8, backgroundColor: '#fff' },
  manualKeyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: DS.surface2,
    borderWidth: 1,
    borderColor: DS.border2,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 20,
    gap: 10,
  },
  manualKey: { flex: 1, fontSize: 10, color: DS.text3, letterSpacing: 1.5, lineHeight: 16 },
  copyBtn: {
    paddingVertical: 4, paddingHorizontal: 10,
    borderRadius: 6, backgroundColor: DS.surface3,
    borderWidth: 1, borderColor: DS.border2,
  },
  copyBtnDone: { backgroundColor: 'rgba(34,197,94,0.12)', borderColor: 'rgba(34,197,94,0.3)' },
  copyBtnLabel: { fontSize: 11, fontWeight: '600', color: DS.text2 },
  copyBtnLabelDone: { color: '#22C55E' },

  codeLabel: { fontSize: 13, fontWeight: '500', color: DS.text1, marginBottom: 8, letterSpacing: -0.1 },
  errorText: { fontSize: 13, color: DS.red, fontWeight: '500', marginTop: 10 },
});
