import { StyleSheet } from 'react-native';
import { DS } from '../../constants/ds';

// Styles for the in-dashboard "Settings" tab (rename org / delete org).
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: DS.bg },
  scroll: {
    padding: 16,
    paddingBottom: 40,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: DS.text3,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  card: {
    backgroundColor: DS.surface2,
    borderWidth: 1,
    borderColor: DS.border,
    borderRadius: 10,
    padding: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: '500',
    color: DS.text1,
    marginBottom: 8,
    letterSpacing: -0.1,
  },
  input: {
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: DS.border2,
    backgroundColor: DS.bg,
    paddingHorizontal: 12,
    fontSize: 14,
    color: DS.text1,
    letterSpacing: -0.1,
    marginBottom: 16,
  },
  errorText: {
    fontSize: 13,
    color: DS.red,
    fontWeight: '500',
    marginBottom: 12,
  },
  confirmText: {
    fontSize: 13,
    color: DS.text2,
    lineHeight: 19,
    marginBottom: 14,
  },
  confirmActions: {
    flexDirection: 'row',
  },
  deleteBtn: {
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.3)',
    backgroundColor: 'rgba(239,68,68,0.07)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteBtnLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: DS.red,
  },

  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: DS.surface2,
    borderWidth: 1,
    borderColor: DS.border,
    borderRadius: 10,
    padding: 16,
    marginBottom: 8,
  },
  navIcon: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: DS.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navLabel: { fontSize: 14, fontWeight: '500', color: DS.text1 },
  navSub: { fontSize: 12, color: DS.text3, marginTop: 2 },
  chevron: { width: 7, height: 12 },
  readOnly: { fontSize: 13, color: DS.text3, fontStyle: 'italic' },

  subHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: DS.border,
  },
  subBack: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  subBackLabel: { fontSize: 14, fontWeight: '500', color: DS.text1, letterSpacing: -0.2 },

  placeholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 60,
  },
  placeholderTitle: { fontSize: 15, color: DS.text2, fontWeight: '500' },
  placeholderHint: { fontSize: 13, color: DS.text3 },
});
